version: '3.3'

services:

  aaw_db:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    container_name: aaw_db
    environment:
      - MARIADB_ROOT_PASSWORD=123
      - MARIADB_DATABASE=aaw_db
      - MARIADB_USER=aaw
      - MARIADB_PASSWORD=2022

  phpmyadmin:
    container_name: aaw_db_client
    links:
      - 'aaw_db:db'
    ports:
      - '8081:80'
    image: phpmyadmin
    depends_on:
      - aaw_db

  aaw_ms:
    build:
      context: ./aaw_ms
      dockerfile: Dockerfile
    container_name: aaw_ms
    ports:
      - '4000:4000'
    image: aaw_ms
    depends_on:
      - aaw_db
    environment:
      - DB_HOST=aaw_db
      - DB_PORT=3306
      - DB_USER=aaw
      - DB_PASSWORD=2022
      - DB_NAME=aaw_db
      - URL=0.0.0.0:4000

  aaw_ag:
    build: ./aaw_ag
    container_name: aaw_ag
    ports:
      - '8082:5000'
    image: aaw_ag

  aaw-ldap:
    image: osixia/openldap:1.5.0 # previous 1.1.8
    container_name: aaw_ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "mdb" # fixed for mac m1 arm64 https://github.com/osixia/docker-openldap/issues/451
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.unal.edu.co"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap_client
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "aaw-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - aaw-ldap

  aaw_proxy:
    build: ./aaw_proxy
    container_name: aaw_proxy
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    restart: always
    logging:
      options:
        max-size: 1g
